name: Hello-Jenkins

on: 
  workflow_dispatch: # This enables the "Run workflow" button

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Hello Jenkins"
